---
# Run basic tests, adapt from aiidalab-launch

name: continuous-integration

on: [push, pull_request]

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install pre-commit==2.11.1
            - name: Run pre-commit
              run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )


    test-package:

        needs: [pre-commit]

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10']

        steps:

            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: |
                  which python
                  python -m pip install -e .[tests]
                  python -m pip freeze
            - name: Run tests
              run: |
                  pytest -v --slow
                  coverage xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  flags: py-${{ matrix.python-version }}